/**
 * Retro Terminal Themes — theme definitions.
 *
 * To add a theme, copy any block in RETRO_THEMES, change the values, done.
 * No other file needs to change. Every theme must provide the same 20 keys:
 * background, foreground, cursor, selection, and the 16 ANSI colors.
 */

export interface RetroTheme {
  name: string;
  year: number;
  description: string;
  colors: Record<string, string>;
}

export const RETRO_THEMES: RetroTheme[] = [
  // ──────────────────────────── 1960s–70s ────────────────────────────
  {
    name: "IBM Mainframe",
    year: 1964,
    description: "System/360 console — cold white and blue phosphor on black",
    colors: {
      "terminal.background": "#0a0e14",
      "terminal.foreground": "#d6e4f0",
      "terminalCursor.foreground": "#9fc4e8",
      "terminal.selectionBackground": "#1e3a5c88",
      "terminal.ansiBlack": "#0a0e14",
      "terminal.ansiRed": "#8fb8de",
      "terminal.ansiGreen": "#a8c8e8",
      "terminal.ansiYellow": "#c2d8ee",
      "terminal.ansiBlue": "#6fa8dc",
      "terminal.ansiMagenta": "#9fc4e8",
      "terminal.ansiCyan": "#b4d2ec",
      "terminal.ansiWhite": "#d6e4f0",
      "terminal.ansiBrightBlack": "#3d5a78",
      "terminal.ansiBrightRed": "#aacdea",
      "terminal.ansiBrightGreen": "#c0daf0",
      "terminal.ansiBrightYellow": "#d8e8f6",
      "terminal.ansiBrightBlue": "#8fc0ec",
      "terminal.ansiBrightMagenta": "#badcf4",
      "terminal.ansiBrightCyan": "#cce4f8",
      "terminal.ansiBrightWhite": "#f0f8ff"
    }
  },
  {
    name: "Punch Card Beige",
    year: 1965,
    description: "IBM punched card stock — dark brown ink on cream manila",
    colors: {
      "terminal.background": "#f3e5c3",
      "terminal.foreground": "#4a3524",
      "terminalCursor.foreground": "#6b4a2f",
      "terminal.selectionBackground": "#d9c49a99",
      "terminal.ansiBlack": "#3a2a1c",
      "terminal.ansiRed": "#9c3c2e",
      "terminal.ansiGreen": "#5c6b34",
      "terminal.ansiYellow": "#8f6a2a",
      "terminal.ansiBlue": "#4a5d78",
      "terminal.ansiMagenta": "#7d4a5c",
      "terminal.ansiCyan": "#4e6e68",
      "terminal.ansiWhite": "#e8d9b5",
      "terminal.ansiBrightBlack": "#6b5844",
      "terminal.ansiBrightRed": "#b5503e",
      "terminal.ansiBrightGreen": "#748244",
      "terminal.ansiBrightYellow": "#a8823a",
      "terminal.ansiBrightBlue": "#5f7694",
      "terminal.ansiBrightMagenta": "#966074",
      "terminal.ansiBrightCyan": "#638a82",
      "terminal.ansiBrightWhite": "#faf2dc"
    }
  },
  {
    name: "DEC VT52 Amber",
    year: 1975,
    description: "Warm amber phosphor glow of DEC video terminals",
    colors: {
      "terminal.background": "#120b00",
      "terminal.foreground": "#ffb000",
      "terminalCursor.foreground": "#ffcc33",
      "terminal.selectionBackground": "#8a5c0066",
      "terminal.ansiBlack": "#120b00",
      "terminal.ansiRed": "#cc6600",
      "terminal.ansiGreen": "#e69500",
      "terminal.ansiYellow": "#ffb000",
      "terminal.ansiBlue": "#a36a00",
      "terminal.ansiMagenta": "#c27c00",
      "terminal.ansiCyan": "#d99e00",
      "terminal.ansiWhite": "#ffc040",
      "terminal.ansiBrightBlack": "#664400",
      "terminal.ansiBrightRed": "#ff8c1a",
      "terminal.ansiBrightGreen": "#ffb733",
      "terminal.ansiBrightYellow": "#ffd11a",
      "terminal.ansiBrightBlue": "#cc9933",
      "terminal.ansiBrightMagenta": "#e6a833",
      "terminal.ansiBrightCyan": "#ffc966",
      "terminal.ansiBrightWhite": "#ffe0a3"
    }
  },
  {
    name: "Apple II Green",
    year: 1977,
    description: "Classic green P1 phosphor of the Apple ][ monitor",
    colors: {
      "terminal.background": "#071004",
      "terminal.foreground": "#33ff33",
      "terminalCursor.foreground": "#66ff66",
      "terminal.selectionBackground": "#1a661a66",
      "terminal.ansiBlack": "#071004",
      "terminal.ansiRed": "#1f9e1f",
      "terminal.ansiGreen": "#33ff33",
      "terminal.ansiYellow": "#29cc29",
      "terminal.ansiBlue": "#1a7a1a",
      "terminal.ansiMagenta": "#24b324",
      "terminal.ansiCyan": "#2ee62e",
      "terminal.ansiWhite": "#5cff5c",
      "terminal.ansiBrightBlack": "#146614",
      "terminal.ansiBrightRed": "#3dff3d",
      "terminal.ansiBrightGreen": "#66ff66",
      "terminal.ansiBrightYellow": "#52ff52",
      "terminal.ansiBrightBlue": "#2eb82e",
      "terminal.ansiBrightMagenta": "#47e647",
      "terminal.ansiBrightCyan": "#70ff70",
      "terminal.ansiBrightWhite": "#adffad"
    }
  },
  // ────────────────────────────── 1980s ──────────────────────────────
  {
    name: "IBM PC DOS",
    year: 1981,
    description: "The original PC-DOS prompt — light grey on true black",
    colors: {
      "terminal.background": "#000000",
      "terminal.foreground": "#aaaaaa",
      "terminalCursor.foreground": "#aaaaaa",
      "terminal.selectionBackground": "#55555588",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#aa0000",
      "terminal.ansiGreen": "#00aa00",
      "terminal.ansiYellow": "#aa5500",
      "terminal.ansiBlue": "#0000aa",
      "terminal.ansiMagenta": "#aa00aa",
      "terminal.ansiCyan": "#00aaaa",
      "terminal.ansiWhite": "#aaaaaa",
      "terminal.ansiBrightBlack": "#555555",
      "terminal.ansiBrightRed": "#ff5555",
      "terminal.ansiBrightGreen": "#55ff55",
      "terminal.ansiBrightYellow": "#ffff55",
      "terminal.ansiBrightBlue": "#5555ff",
      "terminal.ansiBrightMagenta": "#ff55ff",
      "terminal.ansiBrightCyan": "#55ffff",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "Commodore 64",
    year: 1982,
    description: "READY. — light blue text on the famous deep blue screen",
    colors: {
      "terminal.background": "#40318d",
      "terminal.foreground": "#7869c4",
      "terminalCursor.foreground": "#7869c4",
      "terminal.selectionBackground": "#8a7ce088",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#883932",
      "terminal.ansiGreen": "#55a049",
      "terminal.ansiYellow": "#bfce72",
      "terminal.ansiBlue": "#40318d",
      "terminal.ansiMagenta": "#8b3f96",
      "terminal.ansiCyan": "#67b6bd",
      "terminal.ansiWhite": "#9f9f9f",
      "terminal.ansiBrightBlack": "#575757",
      "terminal.ansiBrightRed": "#b86962",
      "terminal.ansiBrightGreen": "#94e089",
      "terminal.ansiBrightYellow": "#ffffb2",
      "terminal.ansiBrightBlue": "#7869c4",
      "terminal.ansiBrightMagenta": "#bf6fc9",
      "terminal.ansiBrightCyan": "#a3e6ed",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "ZX Spectrum",
    year: 1982,
    description: "Sinclair's rubber-key wonder — saturated primaries on black",
    colors: {
      "terminal.background": "#000000",
      "terminal.foreground": "#c8c8c8",
      "terminalCursor.foreground": "#c8c800",
      "terminal.selectionBackground": "#0000c888",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#c80000",
      "terminal.ansiGreen": "#00c800",
      "terminal.ansiYellow": "#c8c800",
      "terminal.ansiBlue": "#0000c8",
      "terminal.ansiMagenta": "#c800c8",
      "terminal.ansiCyan": "#00c8c8",
      "terminal.ansiWhite": "#c8c8c8",
      "terminal.ansiBrightBlack": "#555555",
      "terminal.ansiBrightRed": "#ff0000",
      "terminal.ansiBrightGreen": "#00ff00",
      "terminal.ansiBrightYellow": "#ffff00",
      "terminal.ansiBrightBlue": "#0000ff",
      "terminal.ansiBrightMagenta": "#ff00ff",
      "terminal.ansiBrightCyan": "#00ffff",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "Apple Macintosh",
    year: 1984,
    description: "Hello — crisp black on the light grey of the original Mac",
    colors: {
      "terminal.background": "#eeeeee",
      "terminal.foreground": "#1a1a1a",
      "terminalCursor.foreground": "#1a1a1a",
      "terminal.selectionBackground": "#b3b3b399",
      "terminal.ansiBlack": "#1a1a1a",
      "terminal.ansiRed": "#99201a",
      "terminal.ansiGreen": "#20701e",
      "terminal.ansiYellow": "#8a6d16",
      "terminal.ansiBlue": "#1e3f8a",
      "terminal.ansiMagenta": "#7a2080",
      "terminal.ansiCyan": "#1a7080",
      "terminal.ansiWhite": "#dddddd",
      "terminal.ansiBrightBlack": "#666666",
      "terminal.ansiBrightRed": "#c03028",
      "terminal.ansiBrightGreen": "#2f9430",
      "terminal.ansiBrightYellow": "#a8871e",
      "terminal.ansiBrightBlue": "#2f5ab8",
      "terminal.ansiBrightMagenta": "#9c30a4",
      "terminal.ansiBrightCyan": "#2894a8",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "CGA Magenta",
    year: 1984,
    description: "CGA palette 1 — cyan, magenta, and white on black",
    colors: {
      "terminal.background": "#000000",
      "terminal.foreground": "#ffffff",
      "terminalCursor.foreground": "#ff55ff",
      "terminal.selectionBackground": "#aa00aa77",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#aa00aa",
      "terminal.ansiGreen": "#00aaaa",
      "terminal.ansiYellow": "#aaaaaa",
      "terminal.ansiBlue": "#00aaaa",
      "terminal.ansiMagenta": "#aa00aa",
      "terminal.ansiCyan": "#00aaaa",
      "terminal.ansiWhite": "#aaaaaa",
      "terminal.ansiBrightBlack": "#555555",
      "terminal.ansiBrightRed": "#ff55ff",
      "terminal.ansiBrightGreen": "#55ffff",
      "terminal.ansiBrightYellow": "#ffffff",
      "terminal.ansiBrightBlue": "#55ffff",
      "terminal.ansiBrightMagenta": "#ff55ff",
      "terminal.ansiBrightCyan": "#55ffff",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "Amiga Workbench",
    year: 1985,
    description: "Workbench 1.x — blue-grey desktop with orange and white",
    colors: {
      "terminal.background": "#0055aa",
      "terminal.foreground": "#ffffff",
      "terminalCursor.foreground": "#ff8800",
      "terminal.selectionBackground": "#ff880066",
      "terminal.ansiBlack": "#000020",
      "terminal.ansiRed": "#ff8800",
      "terminal.ansiGreen": "#66aadd",
      "terminal.ansiYellow": "#ffaa33",
      "terminal.ansiBlue": "#003377",
      "terminal.ansiMagenta": "#cc6699",
      "terminal.ansiCyan": "#88bbdd",
      "terminal.ansiWhite": "#dddddd",
      "terminal.ansiBrightBlack": "#446688",
      "terminal.ansiBrightRed": "#ffaa44",
      "terminal.ansiBrightGreen": "#99ccee",
      "terminal.ansiBrightYellow": "#ffcc66",
      "terminal.ansiBrightBlue": "#4488cc",
      "terminal.ansiBrightMagenta": "#ee88bb",
      "terminal.ansiBrightCyan": "#aaddee",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  // ────────────────────────────── 1990s ──────────────────────────────
  {
    name: "Turbo Pascal",
    year: 1990,
    description: "Borland's IDE — yellow on blue, F1 for Help",
    colors: {
      "terminal.background": "#0000a8",
      "terminal.foreground": "#ffff55",
      "terminalCursor.foreground": "#ffff55",
      "terminal.selectionBackground": "#00a8a877",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#a80000",
      "terminal.ansiGreen": "#00a800",
      "terminal.ansiYellow": "#a85400",
      "terminal.ansiBlue": "#0000a8",
      "terminal.ansiMagenta": "#a800a8",
      "terminal.ansiCyan": "#00a8a8",
      "terminal.ansiWhite": "#a8a8a8",
      "terminal.ansiBrightBlack": "#545454",
      "terminal.ansiBrightRed": "#fc5454",
      "terminal.ansiBrightGreen": "#54fc54",
      "terminal.ansiBrightYellow": "#fcfc54",
      "terminal.ansiBrightBlue": "#5454fc",
      "terminal.ansiBrightMagenta": "#fc54fc",
      "terminal.ansiBrightCyan": "#54fcfc",
      "terminal.ansiBrightWhite": "#fcfcfc"
    }
  },
  {
    name: "Windows 3.1",
    year: 1992,
    description: "Program Manager era — white text on navy blue",
    colors: {
      "terminal.background": "#000080",
      "terminal.foreground": "#ffffff",
      "terminalCursor.foreground": "#ffffff",
      "terminal.selectionBackground": "#c0c0c066",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#800000",
      "terminal.ansiGreen": "#008000",
      "terminal.ansiYellow": "#808000",
      "terminal.ansiBlue": "#000080",
      "terminal.ansiMagenta": "#800080",
      "terminal.ansiCyan": "#008080",
      "terminal.ansiWhite": "#c0c0c0",
      "terminal.ansiBrightBlack": "#808080",
      "terminal.ansiBrightRed": "#ff0000",
      "terminal.ansiBrightGreen": "#00ff00",
      "terminal.ansiBrightYellow": "#ffff00",
      "terminal.ansiBrightBlue": "#0000ff",
      "terminal.ansiBrightMagenta": "#ff00ff",
      "terminal.ansiBrightCyan": "#00ffff",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "Norton Commander",
    year: 1993,
    description: "Twin-panel file manager blue with cyan panels and yellow highlights",
    colors: {
      "terminal.background": "#0000a8",
      "terminal.foreground": "#00fcfc",
      "terminalCursor.foreground": "#fcfc54",
      "terminal.selectionBackground": "#00a8a888",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#a80000",
      "terminal.ansiGreen": "#00a800",
      "terminal.ansiYellow": "#fcfc54",
      "terminal.ansiBlue": "#0000a8",
      "terminal.ansiMagenta": "#a800a8",
      "terminal.ansiCyan": "#00a8a8",
      "terminal.ansiWhite": "#a8a8a8",
      "terminal.ansiBrightBlack": "#545454",
      "terminal.ansiBrightRed": "#fc5454",
      "terminal.ansiBrightGreen": "#54fc54",
      "terminal.ansiBrightYellow": "#fcfc54",
      "terminal.ansiBrightBlue": "#5454fc",
      "terminal.ansiBrightMagenta": "#fc54fc",
      "terminal.ansiBrightCyan": "#54fcfc",
      "terminal.ansiBrightWhite": "#fcfcfc"
    }
  },
  {
    name: "Windows 95 Console",
    year: 1995,
    description: "command.com in a window — silver-grey on black",
    colors: {
      "terminal.background": "#010101",
      "terminal.foreground": "#c0c0c0",
      "terminalCursor.foreground": "#c0c0c0",
      "terminal.selectionBackground": "#00008088",
      "terminal.ansiBlack": "#010101",
      "terminal.ansiRed": "#800000",
      "terminal.ansiGreen": "#008000",
      "terminal.ansiYellow": "#808000",
      "terminal.ansiBlue": "#000080",
      "terminal.ansiMagenta": "#800080",
      "terminal.ansiCyan": "#008080",
      "terminal.ansiWhite": "#c0c0c0",
      "terminal.ansiBrightBlack": "#808080",
      "terminal.ansiBrightRed": "#ff0000",
      "terminal.ansiBrightGreen": "#00ff00",
      "terminal.ansiBrightYellow": "#ffff00",
      "terminal.ansiBrightBlue": "#0000ff",
      "terminal.ansiBrightMagenta": "#ff00ff",
      "terminal.ansiBrightCyan": "#00ffff",
      "terminal.ansiBrightWhite": "#ffffff"
    }
  },
  {
    name: "Hacker Green (Matrix)",
    year: 1999,
    description: "Follow the white rabbit — #00ff41 rain on pure black",
    colors: {
      "terminal.background": "#000000",
      "terminal.foreground": "#00ff41",
      "terminalCursor.foreground": "#00ff41",
      "terminal.selectionBackground": "#00802066",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#008f11",
      "terminal.ansiGreen": "#00ff41",
      "terminal.ansiYellow": "#00cc33",
      "terminal.ansiBlue": "#007722",
      "terminal.ansiMagenta": "#00b02d",
      "terminal.ansiCyan": "#00e63a",
      "terminal.ansiWhite": "#4dff79",
      "terminal.ansiBrightBlack": "#003b09",
      "terminal.ansiBrightRed": "#22ff55",
      "terminal.ansiBrightGreen": "#66ff8c",
      "terminal.ansiBrightYellow": "#44ff6e",
      "terminal.ansiBrightBlue": "#00d637",
      "terminal.ansiBrightMagenta": "#33ff61",
      "terminal.ansiBrightCyan": "#7fffa0",
      "terminal.ansiBrightWhite": "#c2ffd1"
    }
  },
  // ────────────────────────────── 2000s ──────────────────────────────
  {
    name: "Windows XP Luna",
    year: 2001,
    description: "Bliss-era soft blues — gentle and friendly",
    colors: {
      "terminal.background": "#dce8f5",
      "terminal.foreground": "#1a3c6e",
      "terminalCursor.foreground": "#2a5caa",
      "terminal.selectionBackground": "#7aa9e699",
      "terminal.ansiBlack": "#1a3c6e",
      "terminal.ansiRed": "#c03535",
      "terminal.ansiGreen": "#3a8a3a",
      "terminal.ansiYellow": "#c98a1e",
      "terminal.ansiBlue": "#2a5caa",
      "terminal.ansiMagenta": "#8a4a9e",
      "terminal.ansiCyan": "#2a8a9e",
      "terminal.ansiWhite": "#c7d9ee",
      "terminal.ansiBrightBlack": "#5a7ba6",
      "terminal.ansiBrightRed": "#e05050",
      "terminal.ansiBrightGreen": "#4faf4f",
      "terminal.ansiBrightYellow": "#e8a832",
      "terminal.ansiBrightBlue": "#3d7ad4",
      "terminal.ansiBrightMagenta": "#a866bd",
      "terminal.ansiBrightCyan": "#3daabf",
      "terminal.ansiBrightWhite": "#f4f9ff"
    }
  },
  {
    name: "OS X Aqua Terminal",
    year: 2001,
    description: "Terminal.app defaults — plain black on white, Aqua era",
    colors: {
      "terminal.background": "#ffffff",
      "terminal.foreground": "#000000",
      "terminalCursor.foreground": "#7f7f7f",
      "terminal.selectionBackground": "#b5d5ff99",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#c23621",
      "terminal.ansiGreen": "#25bc24",
      "terminal.ansiYellow": "#adad27",
      "terminal.ansiBlue": "#492ee1",
      "terminal.ansiMagenta": "#d338d3",
      "terminal.ansiCyan": "#33bbc8",
      "terminal.ansiWhite": "#cbcccd",
      "terminal.ansiBrightBlack": "#818383",
      "terminal.ansiBrightRed": "#fc391f",
      "terminal.ansiBrightGreen": "#31e722",
      "terminal.ansiBrightYellow": "#eaec23",
      "terminal.ansiBrightBlue": "#5833ff",
      "terminal.ansiBrightMagenta": "#f935f8",
      "terminal.ansiBrightCyan": "#14f0f0",
      "terminal.ansiBrightWhite": "#e9ebeb"
    }
  },
  {
    name: "Ubuntu Human",
    year: 2004,
    description: "Warty-era aubergine with Human-theme orange accents",
    colors: {
      "terminal.background": "#300a24",
      "terminal.foreground": "#eeeeec",
      "terminalCursor.foreground": "#f57900",
      "terminal.selectionBackground": "#75507b88",
      "terminal.ansiBlack": "#2e3436",
      "terminal.ansiRed": "#cc0000",
      "terminal.ansiGreen": "#4e9a06",
      "terminal.ansiYellow": "#c4a000",
      "terminal.ansiBlue": "#3465a4",
      "terminal.ansiMagenta": "#75507b",
      "terminal.ansiCyan": "#06989a",
      "terminal.ansiWhite": "#d3d7cf",
      "terminal.ansiBrightBlack": "#555753",
      "terminal.ansiBrightRed": "#ef2929",
      "terminal.ansiBrightGreen": "#8ae234",
      "terminal.ansiBrightYellow": "#fce94f",
      "terminal.ansiBrightBlue": "#729fcf",
      "terminal.ansiBrightMagenta": "#ad7fa8",
      "terminal.ansiBrightCyan": "#34e2e2",
      "terminal.ansiBrightWhite": "#eeeeec"
    }
  },
  {
    name: "Solarized Dark",
    year: 2010,
    description: "Ethan Schoonover's precision dark palette",
    colors: {
      "terminal.background": "#002b36",
      "terminal.foreground": "#839496",
      "terminalCursor.foreground": "#93a1a1",
      "terminal.selectionBackground": "#073642cc",
      "terminal.ansiBlack": "#073642",
      "terminal.ansiRed": "#dc322f",
      "terminal.ansiGreen": "#859900",
      "terminal.ansiYellow": "#b58900",
      "terminal.ansiBlue": "#268bd2",
      "terminal.ansiMagenta": "#d33682",
      "terminal.ansiCyan": "#2aa198",
      "terminal.ansiWhite": "#eee8d5",
      "terminal.ansiBrightBlack": "#002b36",
      "terminal.ansiBrightRed": "#cb4b16",
      "terminal.ansiBrightGreen": "#586e75",
      "terminal.ansiBrightYellow": "#657b83",
      "terminal.ansiBrightBlue": "#839496",
      "terminal.ansiBrightMagenta": "#6c71c4",
      "terminal.ansiBrightCyan": "#93a1a1",
      "terminal.ansiBrightWhite": "#fdf6e3"
    }
  },
  {
    name: "Solarized Light",
    year: 2010,
    description: "The light variant — same 16 colors, inverted base tones",
    colors: {
      "terminal.background": "#fdf6e3",
      "terminal.foreground": "#657b83",
      "terminalCursor.foreground": "#586e75",
      "terminal.selectionBackground": "#eee8d5cc",
      "terminal.ansiBlack": "#073642",
      "terminal.ansiRed": "#dc322f",
      "terminal.ansiGreen": "#859900",
      "terminal.ansiYellow": "#b58900",
      "terminal.ansiBlue": "#268bd2",
      "terminal.ansiMagenta": "#d33682",
      "terminal.ansiCyan": "#2aa198",
      "terminal.ansiWhite": "#eee8d5",
      "terminal.ansiBrightBlack": "#002b36",
      "terminal.ansiBrightRed": "#cb4b16",
      "terminal.ansiBrightGreen": "#586e75",
      "terminal.ansiBrightYellow": "#657b83",
      "terminal.ansiBrightBlue": "#839496",
      "terminal.ansiBrightMagenta": "#6c71c4",
      "terminal.ansiBrightCyan": "#93a1a1",
      "terminal.ansiBrightWhite": "#fdf6e3"
    }
  }
];
